language: ruby
cache: bundler

rvm:
  - 2.2.5

addons:
  code_climate:
    repo_token: '253f38ccb6e5cae38523d1b537038621babe597bab9f78e64a06e0e1319b4b04'

services:
  - postgresql

before_script:
  - psql -c 'create database tasty_brew_test;' -U postgres
  - bundle exec rake db:migrate
  - bundle exec rails s -d

after_success:
  - bundle exec codeclimate-test-reporter
